/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.ligi.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bt_off=0x7f020000;
        public static final int bt_on=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int lcd_green=0x7f020003;
        public static final int starfield=0x7f020004;
    }
    public static final class id {
        public static final int cancel_btn=0x7f060004;
        public static final int check_autoconn=0x7f060002;
        public static final int check_fullscreen=0x7f060015;
        public static final int check_fullspeed=0x7f060005;
        public static final int edit_host=0x7f060000;
        public static final int edit_port=0x7f060001;
        public static final int save_btn=0x7f060003;
        public static final int seek_all=0x7f06000a;
        public static final int seek_back=0x7f060007;
        public static final int seek_front=0x7f060006;
        public static final int seek_left=0x7f060008;
        public static final int seek_right=0x7f060009;
        public static final int stick_progress_0=0x7f06000b;
        public static final int stick_progress_1=0x7f06000c;
        public static final int stick_progress_2=0x7f06000d;
        public static final int stick_progress_3=0x7f06000e;
        public static final int stick_progress_4=0x7f06000f;
        public static final int stick_progress_5=0x7f060010;
        public static final int stick_progress_6=0x7f060011;
        public static final int stick_progress_7=0x7f060012;
        public static final int stick_progress_8=0x7f060013;
        public static final int stick_progress_9=0x7f060014;
    }
    public static final class layout {
        public static final int connection=0x7f030000;
        public static final int motortest=0x7f030001;
        public static final int rcdata=0x7f030002;
        public static final int settings=0x7f030003;
    }
    public static final class raw {
        public static final int voice_sample_01=0x7f040000;
        public static final int voice_sample_02=0x7f040001;
        public static final int voice_sample_03=0x7f040002;
        public static final int voice_sample_04=0x7f040003;
        public static final int voice_sample_05=0x7f040004;
        public static final int voice_sample_06=0x7f040005;
        public static final int voice_sample_07=0x7f040006;
        public static final int voice_sample_08=0x7f040007;
        public static final int voice_sample_09=0x7f040008;
        public static final int voice_sample_10=0x7f040009;
        public static final int voice_sample_11=0x7f04000a;
        public static final int voice_sample_12=0x7f04000b;
        public static final int voice_sample_13=0x7f04000c;
        public static final int voice_sample_komma=0x7f04000d;
        public static final int voice_sample_volt=0x7f04000e;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int map_menu_back_to_list=0x7f050003;
        public static final int map_menu_toggle_street_satellite=0x7f050004;
        public static final int map_menu_zoom_in=0x7f050001;
        public static final int map_menu_zoom_out=0x7f050002;
    }
}
